name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  R-CMD-check:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'release' }
          - { os: macos-latest, r: 'release' }
          # Optional: Add Windows for broader testing if desired
          # - { os: windows-latest, r: 'release' }

    name: R ${{ matrix.config.r }} on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::remotes
            any::testthat
            any::waldo

      - name: Run unit tests via testthat
        run: |
          # Install your package first so its functions are available for tests
          # This assumes your package name can be installed from the current directory.
          Rscript -e 'devtools::install()'
          # Run tests from the 'tests/testthat' directory
          Rscript -e 'testthat::test_dir("tests/testthat", reporter = "summary")'

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          # Fail on R CMD check errors
          error-on: error
          # Arguments for R CMD check (e.g., --no-manual to skip building the manual)
          args: --no-manual
          # Arguments for R CMD build (e.g., --no-manual if you specifically want it for build too)
          build_args: --no-manual # Corrected to use underscore
          # Have the action upload the check results as an artifact
          upload-results: true
          # Customize the name of the uploaded artifact
          artifact-name: R-CMD-check-results-${{ matrix.config.os }}-${{ matrix.config.r }}
