name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  R-CMD-check:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'release' }
          - { os: macos-latest,  r: 'release' }

    name: R ${{ matrix.config.r }} on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::remotes
            any::testthat
            any::waldo

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: error
          args: --no-manual
          build-args: --no-manual
          check-dir: check

      - name: Upload check results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
